export const DELETE_REPORT = 'DELETE_REPORT';
export const SAVE_REPORT = 'SAVE_REPORT';
export const GET_REPORTS = 'GET_REPORTS';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const SAVE_REPORT_SUCCESS = 'SAVE_REPORT_SUCCESS';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const SET_LOADING = 'SET_LOADING';
export const GET_ERROR = 'GET_ERROR';
